import Foundation
import Testing
@testable import RFIsSimple

/// Checks every calculator against an independent implementation.
///
/// `OracleVectors.swift` is generated by `Scripts/qa/reference_model.py`, a
/// separate Python implementation that formulates each relationship
/// differently — free-space path loss through the 32.4478 constant rather than
/// through 4πd/λ, reflection through power ratios rather than the VSWR
/// identity, and so on. Agreement between two independent formulations catches
/// the failure mode a hand-written test cannot: a test that repeats the same
/// mistake as the code it checks.
///
/// This is the numerical half of the QA agent (docs/QA-AGENT.md).
struct OracleConformanceTests {

    @Test(arguments: OracleVectors.all)
    func matchesTheReferenceImplementation(_ testCase: OracleCase) throws {
        let actual = try compute(testCase)

        for (key, expected) in testCase.expected {
            guard let value = actual[key] else {
                Issue.record("\(testCase.calculator): produced no value for \(key)")
                continue
            }
            #expect(
                matches(value, expected, tolerance: testCase.tolerance),
                "\(testCase.calculator).\(key) — got \(value), reference says \(expected) (inputs \(testCase.inputs))"
            )
        }
    }

    /// Every case in the vectors should also be one the app accepts: a throw
    /// here means the app rejects an input the reference considers valid.
    @Test func noReferenceCaseIsRejected() throws {
        for testCase in OracleVectors.all {
            #expect(throws: Never.self, "\(testCase.calculator) rejected \(testCase.inputs)") {
                _ = try compute(testCase)
            }
        }
    }

    @Test func theVectorsCoverEveryCalculator() {
        let covered = Set(OracleVectors.all.map(\.calculator))
        let expected: Set<String> = [
            "power", "voltagePower", "wave", "fspl", "linkBudget", "radiatedPower",
            "thermalNoise", "sensitivity", "reflection", "cascade", "aperture", "fieldRegions"
        ]
        #expect(covered == expected, "Missing coverage: \(expected.subtracting(covered))")
        #expect(OracleVectors.all.count > 250)
    }

    // MARK: - Comparison

    /// Relative comparison, falling back to an absolute one where both values
    /// are essentially zero — a relative tolerance is meaningless there, and
    /// `10·log10(1)` lands a few ULPs either side of exactly 0.
    private func matches(_ actual: Double, _ expected: Double, tolerance: Double) -> Bool {
        guard actual.isFinite, expected.isFinite else { return false }
        let difference = abs(actual - expected)
        let scale = max(abs(actual), abs(expected))
        if scale < 1e-9 { return difference < 1e-11 }
        return difference <= tolerance * scale
    }

    // MARK: - Dispatch

    /// Runs the app's calculator for a case and flattens the result into the
    /// same key names the reference implementation uses.
    private func compute(_ testCase: OracleCase) throws -> [String: Double] {
        func input(_ key: String) throws -> Double {
            guard let value = testCase.inputs[key] else {
                throw CalculationError.missingValue(quantity: key)
            }
            return value
        }
        func index<T: CaseIterable>(_ key: String, _ type: T.Type) throws -> T {
            let raw = Int(try input(key))
            let cases = Array(T.allCases)
            guard raw >= 0, raw < cases.count else {
                throw CalculationError.outOfRange(quantity: key, requirement: "a valid case index")
            }
            return cases[raw]
        }

        switch testCase.calculator {
        case "power":
            let unit = try index("unit", PowerUnit.self)
            let conversion = try PowerConversion.from(value: try input("value"), unit: unit)
            var out: [String: Double] = [
                "watts": conversion.watts,
                "milliwatts": conversion.milliwatts,
                "microwatts": conversion.microwatts
            ]
            out["dBm"] = conversion.dBm
            out["dBW"] = conversion.dBW
            return out

        case "voltagePower":
            let quantity = try index("quantity", VoltagePowerQuantity.self)
            let solution = try VoltagePowerCalculator.solve(
                from: quantity,
                value: try input("value"),
                impedanceOhms: try input("impedance")
            )
            var out: [String: Double] = [
                "watts": solution.watts,
                "rmsVolts": solution.rmsVolts,
                "peakVolts": solution.peakVolts,
                "peakToPeakVolts": solution.peakToPeakVolts
            ]
            out["dBm"] = solution.dBm
            out["dBmV"] = solution.dBmV
            out["dBuV"] = solution.dBµV
            return out

        case "wave":
            let quantity = try index("quantity", WaveQuantity.self)
            let solution = try WaveCalculator.solve(
                from: quantity,
                value: try input("value"),
                velocityFactor: try input("velocityFactor")
            )
            return [
                "frequencyHz": solution.frequencyHz,
                "periodSeconds": solution.periodSeconds,
                "wavelengthMetres": solution.wavelengthMetres,
                "quarterWavelengthMetres": solution.quarterWavelengthMetres,
                "velocity": solution.velocity
            ]

        case "fspl":
            let solution = try PathLossCalculator.freeSpace(
                frequencyHz: try input("frequency"),
                distanceMetres: try input("distance")
            )
            return [
                "lossDB": solution.lossDB,
                "wavelengthMetres": solution.wavelengthMetres,
                "minimumValidDistanceMetres": solution.minimumValidDistanceMetres
            ]

        case "linkBudget":
            let solution = try LinkBudgetCalculator.solve(
                LinkBudgetInput(
                    transmitPowerDBm: try input("ptx"),
                    transmitLossDB: try input("ltx"),
                    transmitGainDBi: try input("gtx"),
                    pathLossDB: try input("lpath"),
                    receiveGainDBi: try input("grx"),
                    receiveLossDB: try input("lrx"),
                    sensitivityDBm: testCase.inputs["sensitivity"]
                )
            )
            var out: [String: Double] = [
                "receivedPowerDBm": solution.receivedPowerDBm,
                "eirpDBm": solution.eirpDBm
            ]
            out["marginDB"] = solution.marginDB
            return out

        case "radiatedPower":
            let solution = try RadiatedPowerCalculator.solve(
                transmitPowerDBm: try input("ptx"),
                feedLossDB: try input("feedLoss"),
                antennaGain: try input("gain"),
                reference: try index("reference", GainReference.self)
            )
            return [
                "eirpDBm": solution.eirpDBm,
                "erpDBm": solution.erpDBm,
                "antennaGainDBi": solution.antennaGainDBi,
                "eirpWatts": solution.eirpWatts
            ]

        case "thermalNoise":
            let solution = try NoiseCalculator.thermalNoise(
                bandwidthHz: try input("bandwidth"),
                temperatureKelvin: try input("temperature"),
                noiseFigureDB: testCase.inputs["noiseFigure"]
            )
            var out: [String: Double] = [
                "noiseDBm": solution.noiseDBm,
                "densityDBmPerHz": solution.densityDBmPerHz
            ]
            out["floorDBm"] = solution.floorDBm
            return out

        case "sensitivity":
            let solution = try NoiseCalculator.sensitivity(
                bandwidthHz: try input("bandwidth"),
                noiseFigureDB: try input("noiseFigure"),
                requiredSNRDB: try input("snr"),
                temperatureKelvin: try input("temperature")
            )
            return [
                "sensitivityDBm": solution.sensitivityDBm,
                "noiseFloorDBm": solution.noiseFloorDBm,
                "thermalNoiseDBm": solution.thermalNoiseDBm,
                "equivalentNoiseTemperature": solution.equivalentNoiseTemperature
            ]

        case "reflection":
            let quantity = try index("quantity", ReflectionQuantity.self)
            let solution = try ReflectionCalculator.solve(from: quantity, value: try input("value"))
            var out: [String: Double] = [
                "gamma": solution.gamma,
                "reflectedPowerPercent": solution.reflectedPowerPercent,
                "transmittedPowerPercent": solution.transmittedPowerPercent
            ]
            out["vswr"] = solution.vswr
            out["returnLossDB"] = solution.returnLossDB
            out["mismatchLossDB"] = solution.mismatchLossDB
            return out

        case "cascade":
            guard let gains = testCase.arrayInputs["gains"],
                  let noiseFigures = testCase.arrayInputs["noiseFigures"],
                  gains.count == noiseFigures.count else {
                throw CalculationError.missingValue(quantity: "stages")
            }
            let stages = zip(gains, noiseFigures).map {
                CascadeStage(gainDB: $0, noiseFigureDB: $1)
            }
            let solution = try CascadeCalculator.solve(stages: stages)
            return [
                "totalGainDB": solution.totalGainDB,
                "totalNoiseFigureDB": solution.totalNoiseFigureDB,
                "equivalentNoiseTemperature": solution.equivalentNoiseTemperature
            ]

        case "aperture":
            let solution = try AntennaCalculator.effectiveAperture(
                frequencyHz: try input("frequency"),
                gainDBi: try input("gain")
            )
            return [
                "apertureSquareMetres": solution.apertureSquareMetres,
                "apertureSquareCentimetres": solution.apertureSquareCentimetres,
                "wavelengthMetres": solution.wavelengthMetres,
                "equivalentCircleDiameterMetres": solution.equivalentCircleDiameterMetres
            ]

        case "fieldRegions":
            let solution = try AntennaCalculator.fieldRegions(
                frequencyHz: try input("frequency"),
                largestDimensionMetres: try input("dimension")
            )
            return [
                "reactiveBoundaryMetres": solution.reactiveBoundaryMetres,
                "fraunhoferBoundaryMetres": solution.fraunhoferBoundaryMetres,
                "smallAntennaBoundaryMetres": solution.smallAntennaBoundaryMetres,
                "wavelengthMetres": solution.wavelengthMetres,
                "practicalFarFieldMetres": solution.practicalFarFieldMetres
            ]

        default:
            throw CalculationError.outOfRange(
                quantity: testCase.calculator,
                requirement: "a calculator this test knows how to run"
            )
        }
    }
}
